DEVICE_PATH := device/motorola/devonf

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a

TARGET_BOARD_PLATFORM := mt6855

TARGET_SUPPORTS_64_BIT_APPS := true
TARGET_USES_64_BIT_BINDER := true

TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true
TARGET_NO_KERNEL := false
TARGET_NO_RECOVERY := false

BOARD_USES_RECOVERY_AS_BOOT := true
BOARD_BOOTIMG_HEADER_VERSION := 4

BOARD_KERNEL_BASE := 0x40078000
BOARD_KERNEL_PAGESIZE := 4096
BOARD_KERNEL_IMAGE_NAME := Image.gz-dtb

BOARD_KERNEL_CMDLINE := androidboot.hardware=mt6855

TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel

TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery.fstab

BOARD_BUILD_SYSTEM_ROOT_IMAGE := false
BOARD_SUPPRESS_SECURE_ERASE := true
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_HAS_NO_SELECT_BUTTON := true

RECOVERY_SDCARD_ON_DATA := true

BOARD_SUPER_PARTITION_SIZE := 9126805504
BOARD_SUPER_PARTITION_GROUPS := moto_dynamic_partitions

BOARD_MOTO_DYNAMIC_PARTITIONS_SIZE := 9122611200
BOARD_MOTO_DYNAMIC_PARTITIONS_PARTITION_LIST := \
    system \
    vendor \
    product \
    odm \
    system_ext

TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_PRODUCT := product
TARGET_COPY_OUT_SYSTEM_EXT := system_ext
TARGET_COPY_OUT_ODM := odm

BOARD_FLASH_BLOCK_SIZE := 262144

TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

TW_THEME := portrait_hdpi
TW_EXTRA_LANGUAGES := true
TW_USE_TOOLBOX := true
TW_HAS_MTP := true
TW_INCLUDE_FASTBOOTD := true

TW_INCLUDE_RECOVERY_FSTAB := true
TW_BUILD_RECOVERY_IMAGE := true

TW_INCLUDE_CRYPTO := true
TW_INCLUDE_NTFS := true

AB_OTA_UPDATER := true
BOARD_USES_METADATA_PARTITION := true

TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TW_DEFAULT_LANGUAGE := pt_BR
TW_NO_SCREEN_BLANK := true
TW_SCREEN_BLANK_ON_BOOT := false
TW_INPUT_BLACKLIST := "hbtp_vm"
