DEVICE_PATH := device/motorola/devonf

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_VARIANT := generic

TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=

TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true

BOARD_HAS_LARGE_FILESYSTEM := true

BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 67108864

TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel

BOARD_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery.fstab

TW_THEME := portrait_hdpi
TW_INCLUDE_NTFS := true
TW_INCLUDE_CRYPTO := true
