name: Continue Build TWRP Devonf

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Free disk space WITHOUT deleting twrp
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/lib/android
          sudo docker image prune -af || true
          sudo apt clean
          df -h

      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y \
          git curl zip unzip ccache automake lzop \
          bison gperf build-essential \
          zlib1g-dev gcc-multilib g++-multilib \
          libc6-dev-i386 \
          x11proto-dev libx11-dev \
          libgl1-mesa-dev libxml2-utils xsltproc \
          openjdk-11-jdk python3 rsync \
          libncurses-dev

      - name: Install repo
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod +x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Restore source if missing
        run: |
          if [ ! -d twrp ]; then
            mkdir twrp
            cd twrp

            repo init \
            -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git \
            -b twrp-12.1 \
            --git-lfs

            repo sync -c --force-sync --no-clone-bundle --no-tags -j2

            git clone \
            https://github.com/Herick12/android_device_motorola_devonf.git \
            device/motorola/devonf
          fi

      - name: Continue build
        run: |
          cd twrp

          find hardware/interfaces -name "Android.bp" \
          -exec sed -i '/vts_proto_fuzzer_default/d' {} \; || true

          find vendor/qcom -name "Android.bp" \
          -exec sed -i '/vts_proto_fuzzer_default/d' {} \; || true

          source build/envsetup.sh

          export ALLOW_MISSING_DEPENDENCIES=true
          export SOONG_ALLOW_MISSING_DEPENDENCIES=true
          export TARGET_BUILD_APPS=""
          export SKIP_ABI_CHECKS=true
          export TARGET_NO_TESTS=true
          export SKIP_CTS_TESTS=true
          export BUILD_BROKEN_DUP_RULES=true
          export BUILD_BROKEN_MISSING_REQUIRED_MODULES=true

          lunch omni_devonf-eng

          mka recoveryimage vendorbootimage bootimage -j2 || true

          echo "=== TODOS OS .IMG GERADOS ==="
          find out/target/product/devonf/ -name "*.img"

      - name: Prepare upload
        run: |
          mkdir -p upload

          find twrp/out/target/product/devonf/ \
          -name "*.img" \
          -exec cp {} upload/ \;

          echo "=== ARQUIVOS PARA UPLOAD ==="
          ls -lah upload/

      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: twrp-devonf
          path: upload/
