name: Build TWRP Devonf Fixed

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free huge disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/share/swift
          sudo rm -rf /usr/lib/jvm
          sudo rm -rf /opt/hostedtoolcache
          sudo docker system prune -af || true
          sudo apt clean
          sudo swapoff -a || true
          df -h

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git curl zip unzip ccache automake lzop \
            bison gperf build-essential \
            zlib1g-dev gcc-multilib g++-multilib \
            libc6-dev-i386 \
            x11proto-dev libx11-dev \
            libgl1-mesa-dev libxml2-utils xsltproc \
            openjdk-11-jdk python3 rsync \
            libncurses-dev bc flex libssl-dev \
            repo

      - name: Init repo
        run: |
          mkdir twrp
          cd twrp

          repo init \
            -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git \
            -b twrp-12.1 \
            --depth=1

      - name: Add local manifest
        run: |
          mkdir -p twrp/.repo/local_manifests

          cat > twrp/.repo/local_manifests/roomservice.xml <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <manifest>
            <project
              name="Herick12/android_device_motorola_devonf"
              path="device/motorola/devonf"
              remote="github"
              revision="main" />
          </manifest>
          EOF

      - name: Repo sync
        run: |
          cd twrp

          repo sync \
            -c \
            --force-sync \
            --optimized-fetch \
            --no-clone-bundle \
            --no-tags \
            --prune \
            -j2

      - name: Patch BoardConfig
        run: |
          cd twrp

          sed -i
          
